spring:
  profiles:
    active: dev
  mvc:
    # ???????
    static-path-pattern: /static/**
  thymeleaf:
    cache: false

server:
  servlet:
    # session??????(?)????30
    session:
      timeout: 3600s
    #   ??????
    context-path: /
  # ???????????????URL????BasicErrorController????
  error:
    path: /error
  # ?????IP???????????????IP?????????????????????????
  # address:
  tomcat:
    # tomcat?URL??
    uri-encoding: UTF-8
  port: 8085
mybatis:
  # ??mybatis???
  mapper-locations: classpath*:mapper/**/*Mapper.xml
